version: v2beta1
name: dinsro

vars:
  REPO:
    default: duck1123
  PROJECT:
    default: dinsro
  DEVIMAGE_PROJECT:
    default: devimage
  REGISTRY:
    question: Where is the registry used by you local cluster
    default: "k3d-myregistry.localtest.me:12345"
  USE_PERSISTENCE:
    default: false

pipelines:
  build-devimage: |-
    build_images devimage

  create-chart-directories: |-
    mkdir -p target/charts

  create-namespace: |-
    NAME=dinsro
    kubectl create namespace ${NAME} || true

  deploy: |-
    run_dependencies --all
    run_pipelines deploy-dinsro

  deploy-all: |-
    run_dependencies --all
    run_pipelines deploy-all-bitcoin
    run_pipelines deploy-dinsro

  deploy-all-bitcoin: |-
    NAME=alice run_pipelines deploy-bitcoin
    NAME=bob run_pipelines deploy-bitcoin

  deploy-bitcoin: |-
    echo ""
    echo "=== Deploying Bitcoin Stack: ${NAME?Name not set} ==="
    run_pipelines deploy-bitcoind
    run_pipelines deploy-lnd
    run_pipelines deploy-fileserver
    run_pipelines deploy-rtl

  deploy-bitcoind: |-
    echo ""
    echo "--- Deployng Bitcoind for ${NAME?Name not set} ---"
    echo ""
    run_pipelines create-namespace
    run_pipelines create-chart-directories
    YAML_PATH=target/charts/${NAME}_bitcoind.yaml
    bb helm-bitcoin ${NAME} > ${YAML_PATH}
    kubectl apply -f ${YAML_PATH}
    # kubectl apply --namespace ${NAME} -f ${YAML_PATH}

  deploy-database: |-
    run_pipelines deploy-postgres

  deploy-dinsro: |-
    echo ""
    echo "--- Deploying Dinsro ---"
    echo ""
    bb generate-dinsro-values
    build_images dinsro
    create_deployments dinsro

  deploy-fileserver: |-
    echo ""
    echo "--- Deploying Fileserver for ${NAME?Name not set} ---"
    echo ""
    run_pipelines create-namespace
    run_pipelines create-chart-directories
    YAML_PATH=target/charts/${NAME}_fileserver.yaml
    bb helm-fileserver ${NAME} > ${YAML_PATH}
    kubectl apply -f ${YAML_PATH}
    # kubectl apply --namespace ${NAME} -f ${YAML_PATH}

  deploy-lnd: |-
    echo ""
    echo "--- Deploying LND for ${NAME?Name not set} ---"
    echo ""
    run_pipelines create-namespace
    run_pipelines create-chart-directories
    YAML_PATH=target/charts/${NAME}_lnd.yaml
    bb helm-lnd ${NAME} > ${YAML_PATH}
    kubectl apply -f ${YAML_PATH}
    # kubectl apply --namespace ${NAME} -f ${YAML_PATH}

  deploy-postgres: |-
    echo ""
    echo "--- Deploying Postgres ---"
    echo ""
    create_deployments postgres

  deploy-rtl: |-
    echo ""
    echo "--- Deploying RTL for ${NAME?Name not set} ---"
    echo ""
    run_pipelines create-namespace
    run_pipelines create-chart-directories
    YAML_PATH=target/charts/${NAME}_rtl.yaml
    bb generate-rtl-values ${NAME}
    bb helm-rtl ${NAME} > ${YAML_PATH}
    kubectl apply -f ${YAML_PATH}
    # kubectl apply --namespace ${NAME} -f ${YAML_PATH}

  dev: |-
    echo "Starting dev"
    bb generate-dinsro-values
    run_dependencies --all
    create_deployments dinsro
    start_dev app

  dev-all: |-
    run_pipelines deploy-all-bitcoin
    run_pipelines dev

  purge: |-
    echo "-- Purging Dinsro --"
    purge_deployments dinsro

  purge-all: |-
    run_pipelines purge
    run_pipelines purge-devimage
    run_pipelines purge-all-bitcoin

  purge-all-bitcoin: |-
    NAME=alice run_pipelines purge-bitcoin
    NAME=bob run_pipelines purge-bitcoin

  purge-bitcoin: |-
    echo ""
    echo "=== Purging Bitcoin stack for ${NAME?name not set} ==="
    run_pipelines purge-bitcoind
    run_pipelines purge-fileserver
    run_pipelines purge-lnd
    run_pipelines purge-rtl

  purge-bitcoind: |-
    echo ""
    echo "--- Purging Bitcoind for ${NAME?Name not set} ---"
    echo ""
    YAML_PATH=target/charts/${NAME?}_bitcoind.yaml
    kubectl delete -f ${YAML_PATH} || true
    # kubectl delete --namespace ${NAME} -f ${YAML_PATH} || true

  purge-database: |-
    echo ""
    echo "=== Purging Database ==="
    purge_deployments postgres

  purge-devimage: |-
    echo "=== Purging Devimage ==="
    kubectl delete deployments dinsro-devspace || true

  purge-dinsro: |-
    echo ""
    echo "Purge Dinsro"
    purge_deployments dinsro

  purge-fileserver: |-
    echo ""
    echo "--- Purging fileserver for ${NAME?Name not set} ---"
    echo ""
    YAML_PATH=target/charts/${NAME?}_fileserver.yaml
    kubectl delete -f ${YAML_PATH} || true
    # kubectl delete --namespace ${NAME?} -f ${YAML_PATH} || true

  purge-lnd: |-
    echo ""
    echo "--- Purging LND for ${NAME?} ---"
    echo ""
    YAML_PATH=target/charts/${NAME}_lnd.yaml
    kubectl delete -f ${YAML_PATH} || true
    # kubectl delete --namespace ${NAME} -f ${YAML_PATH} || true

  purge-rtl: |-
    echo ""
    echo "--- Purging RTL for ${NAME} ---"
    echo ""
    YAML_PATH=target/charts/${NAME}_rtl.yaml
    kubectl delete -f ${YAML_PATH} || true
    # kubectl delete --namespace ${NAME} -f ${YAML_PATH} || true

images:
  dinsro:
    image: ${REGISTRY}/${REPO}/${PROJECT}
    custom:
      command: |-
        set -ex
        export TAG=${runtime.images.dinsro.tag}
        export IMAGE=${REPO}/${PROJECT}

        earthly +image --repo ${REPO} --project ${PROJECT} --tag ${TAG}

        docker tag ${IMAGE}:${TAG} ${REGISTRY}/${IMAGE}:${TAG}
        docker push ${REGISTRY}/${IMAGE}:${TAG}
        docker image rm ${IMAGE}:${TAG}
        docker image rm ${REGISTRY}/${IMAGE}:${TAG}
  sources:
    image: ${REGISTRY}/${REPO}/${PROJECT}-sources
    custom:
      command: |-
        set -ex
        export TAG=${runtime.images.sources.tag}
        export IMAGE=${REPO}/${PROJECT}-sources

        earthly +dev-sources-image --REPO ${REPO} --PROJECT ${PROJECT}-sources --TAG ${TAG}

        docker tag ${IMAGE}:${TAG} ${REGISTRY}/${IMAGE}:${TAG}
        docker push ${REGISTRY}/${IMAGE}:${TAG}
        docker image rm ${IMAGE}:${TAG}
        docker image rm ${REGISTRY}/${IMAGE}:${TAG}

  devcards:
    image: ${REPO}/dinsro-devcards:devcards-latest
    custom:
      command: |-
        echo "Building devcards"
        earthly +devcards-image
  # devimage:
  #   image: ${REPO}/${DEVIMAGE_PROJECT}
  #   custom:
  #     command: |-
  #       set -ex
  #       echo "building devimage"
  #       export TAG=${runtime.images.devimage.tag}
  #       export IMAGE=${REPO}/${DEVIMAGE_PROJECT}

  #       earthly +devspace-base --repo ${REPO} --project ${DEVIMAGE_PROJECT} --tag ${TAG}

  #       docker tag ${IMAGE}:${TAG} ${REGISTRY}/${IMAGE}:${TAG}
  #       docker push ${REGISTRY}/${IMAGE}:${TAG}
  #       docker image rm ${IMAGE}:${TAG}
  #       docker image rm ${REGISTRY}/${IMAGE}:${TAG}

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  dinsro:
    helm:
      chart:
        # name: dinsro
        # repo: https://chart.kronkltd.net/
        # version: 0.1.4
        name: ./resources/helm/dinsro/
      valuesFiles:
      - "target/dinsro_values.yaml"
      values:
        image:
          repository: ${runtime.images.dinsro.image}
          tag: ${runtime.images.dinsro.tag}
        devcards:
          enabled: false
        devtools:
          enabled: false
        docs:
          enabled: false
        logLevel: ":trace"
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            ingress.kubernetes.io/force-ssl-redirect: "true"
          tls:
          - hosts:
            - dinsro.dev.kronkltd.net
            secretName: dinsro-tls
        notebooks:
          enabled: true
          ingress:
            enabled: true

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # imageSelector: duck1123/dinsro
    # devImage: ${REGISTRY}/${REPO}/${DEVIMAGE_PROJECT}:${runtime.images.devimage.tag}
    # devImage: ${REGISTRY}/${REPO}/${DEVIMAGE_PROJECT}
    devImage: ${REPO}/${DEVIMAGE_PROJECT}:latest
    labelSelector:
      app.kubernetes.io/name: dinsro
      app.kubernetes.io/instance: dinsro
    sync:
    - path: ./
      excludePaths:
      - node_modules/
    terminal:
      command: ./devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
    - command: devspace
    - command: kubectl
    - command: helm
    # - command: git
    ports:
    # Dinsro Main interface
    - port: "3000"
    - port: "3691"
    - port: "3692"
    # Workspaces
    - port: "3693"
    - port: "7000"
    - port: "7777"
    # CLJ nRepl
    - port: "7778"
    - port: "8000"
    # Shadow Dashboard
    - port: "9630"
    # Tilt
    - port: "10350"
    open:
    - url: http://localhost:10350

# Use the `commands` section to define repeatable dev workflows for this project
commands:
  build-devimage:
    command: earthly --push +devspace-base
  deploy:
    command: devspace run-pipeline deploy || true
  deploy-all:
    command: devspace run-pipeline deploy-all || true
  deploy-alice:
    command: NAME=alice devspace run-pipeline deploy-bitcoin || true
  deploy-bitcoin:
    command: devspace run-pipeline deploy-all-bitcoin || true
  deploy-bob:
    command: NAME=bob devspace run-pipeline deploy-bitcoin || true
  deploy-database:
    command: devspace run-pipeline deploy-database
  deploy-postgres:
    command: devspace run-pipeline deploy-postgres
  dev:
    command: devspace enter -- bash -c 'byobu'
  dev-all:
    command: devspace run-pipelines dev-all
  test:
    command: bb test
  lint:
    command: bb lint
  purge:
    command: devspace run-pipeline purge
  purge-all:
    command: devspace run-pipeline purge-all
  purge-bitcoin:
    command: devspace run-pipeline purge-all-bitcoin
  purge-dinsro:
    command: devspace run-pipeline purge-dinsro
  purge-alice:
    command: NAME=alice devspace run-pipeline purge-bitcoin || true
  purge-bob:
    command: NAME=bob devspace run-pipeline purge-bitcoin || true
  purge-database:
    command: devspace run-pipeline purge-database || true
  purge-devimage:
    command: devspace run-pipeline purge-devimage || true
  start:
    command: devspace enter -- bash -c 'bb clean && bb run'
