# FROM clojure
FROM theasp/clojurescript-nodejs:latest

LABEL maintainer="Duck Nebuchadnezzar <duck@kronkltd.net>"
MAINTAINER Duck Nebuchadnezzar <duck@kronkltd.net>

WORKDIR /usr/src/app

RUN npm install -g karma
RUN npm install -g karma-chrome-launcher
RUN npm install -g karma-cljs-test

ADD project.clj /usr/src/app/project.clj
RUN lein deps

ADD package.json /usr/src/app/package.json
ADD package-lock.json /usr/src/app/package-lock.json
RUN npm install

ADD . /usr/src/app

RUN mkdir -p /home/duck/projects/dinsro/data/dev
RUN mkdir -p /home/duck/projects/dinsro/data/test
RUN script/test
RUN script/test-javascript
