# .circleci/config.yml

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Log in to Docker
          command: |
            docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
      - run:
          name: Install Clojure
          command: |
            sudo apt update
            sudo apt install bash curl rlwrap openjdk-17-jdk
            curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
            chmod +x linux-install-1.11.1.1273.sh
            sudo ./linux-install-1.11.1.1273.sh
      - run:
          name: Install Earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
      - run:
          name: Show Earthly version
          command: |
            earthly --version
      - run:
          name: Display Clojure version
          command: |
            which clojure
            clojure --version
      - run:
          name: Display Build Version
          command: |
            clojure -T:build print-version
      - run:
          name: Prepare Base Task
          command: |
            earthly -P --remote-cache=duck1123/dinsro:cache +builder
      - run:
          name: Check Source
          command: |
            earthly -P +check
      - run:
          name: Lint Source
          command: |
            earthly -P +lint
      - run:
          name: Run Tests
          command: |
            earthly -P +test
      - run:
          name: Build Cert Downloader
          command: |
            earthly -P +cert-downloader
      - run:
          name: Build Fileserver
          command: |
            earthly -P +fileserver
      - run:
          name: Build Devspace Image
          command: |
            earthly -P +devspace-base
      - run:
          name: Build Devcards Image
          command: |
            earthly -P +devcards-image
      - run:
          name: Build Docs Image
          command: |
            earthly -P +docs-image
      - run:
          name: Build Jar
          command: |
            earthly -P +jar
      - run:
          name: Build Main Image
          command: |
            export BUILD_VERSION=$(clojure -T:build print-version)
            earthly -P +image --tag ${BUILD_VERSION?}
      - run:
          name: Push Images
          command: |
            export BUILD_VERSION=$(clojure -T:build print-version)
            earthly -P --remote-cache=duck1123/dinsro:cache --push +all-images --tag ${BUILD_VERSION?}
            earthly -P --remote-cache=duck1123/dinsro:cache --push +all-images --tag latest
