# .circleci/config.yml

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - run: earthly --version
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +cert-downloader
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +fileserver
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +check
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +lint
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +test
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +devspace-base
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +devcards-image
      - run: earthly -P --remote-cache=duck1123/dinsro:cache --push +docs-image
