# .circleci/config.yml

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Log in to Docker
          command: |
            docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
      - run:
          name: Install Clojure
          command: |
            sudo apt update
            sudo apt install bash curl rlwrap openjdk-17-jdk
            curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
            chmod +x linux-install-1.11.1.1273.sh
            sudo ./linux-install-1.11.1.1273.sh
      - run:
          name: Install Earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
      - run:
          name: Show Earthly version
          command: |
            earthly --version
      - run:
          name: Display Clojure version
          command: |
            which clojure
            clojure --version
      - run:
          name: Display Build Version
          command: |
            clojure -T:build print-version
      - run:
          name: Prepare Base Task
          command: |
            earthly -P --remote-cache=duck1123/dinsro:cache +builder
      - run:
          name: Validate
          command: |
            earthly -P +validate
      - run:
          name: Build Support Images
          command: |
            earthly -P +support-images
      - run:
          name: Build Jar
          command: |
            earthly -P +jar
      - store_artifacts:
          path: target/dinsro.jar
          destination: dinsro.jar
      - run:
          name: Push Images
          command: |
            export BUILD_VERSION=$(clojure -T:build print-version)
            earthly -P --remote-cache=duck1123/dinsro:cache --push +all-images --tag ${BUILD_VERSION?}
            docker tag duck1123/dinsro:${BUILD_VERSION} duck1123/dinsro:latest
            docker push duck1123/dinsro:latest
