apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fileserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fileserver.name" . }}
    chart: {{ template "fileserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "fileserver.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fileserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: "fileserver"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          volumeMounts:
          - name: data
            mountPath: /mnt/lnd-data
            subPath: .lnd
          ports:
          - name: files
            containerPort: 3000
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "fileserver.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
