{{- if and .Values.docs.enabled .Values.docs.ingress.enabled -}}
{{- $fullName := include "dinsro.fullname" . -}}
{{- $svcPort := .Values.docs.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "dinsro.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.docs.ingress.tls }}
  tls:
  {{- range .Values.docs.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.docs.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: docs
            port:
              name: docs
      {{- end }}
  {{- end }}
{{- end }}
