#!/usr/bin/env bash

set -ex

rm -rf target
rm -rf .shadow-cljs/builds
rm -rf resources/reframe/public/js
rm -rf resources/reframe-cards/public/js
rm -rf resources/reframe-workspaces/public/js
rm -rf classes/*
