(ns dinsro.all-tests
  (:require
   dinsro.ui-test
   dinsro.ui.admin.users.categories-test
   dinsro.ui.breadcrumbs-test
   dinsro.ui.core.blocks-test
   dinsro.ui.core.nodes-test
   dinsro.ui.core.nodes.transactions-test
   dinsro.ui.core.nodes.wallets-test
   dinsro.ui.core.wallets-test
   dinsro.ui.core.words-test
   dinsro.ui.forms.registration-test
   dinsro.ui.navbars-test
   dinsro.ui.nostr.event-tags-test
   dinsro.ui.nostr.events-test
   dinsro.ui.nostr.pubkeys-test
   dinsro.ui.registration-test
   dinsro.ui.settings.ln.peers-test
   dinsro.ui.transactions-test
   dinsro.ui.transactions.debits-test))
