apiVersion: v1
kind: Service
metadata:
  name: {{ include "nostream.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "nostream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nostream.selectorLabels" . | nindent 4 }}
